remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Fireside Chat: The Future of Fintech and the Impact of GenAI
description: List of 10 Questions for a Fireside Chat on the Future of Fintech and the Impact of GenAI
